language: cpp
compiler:
  - clang

matrix:
  include:
    - os: osx
    - os: linux
      before_install:
        - sudo apt-get install python2.7

script:
  - ./compile_clang.sh
  - cd test
  - ./compile_clang.sh
  - ./build/testencode
  - python setup.py
  - python run.py