language: cpp
compiler:
  - clang

matrix:
  include:
    - os: osx
      before_install:
        - brew install python

    - os: linux
      before_install:
        - sudo apt-get install python2.7

script:
  - ./compile_clang.sh
  - cd test
  - ./compile_clang.sh
  - ./build/testencode
  - python setup.py
