platform:
  - x86
  - x64

install:

before_build:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build_script:
  - compile_cl.bat
  - cd test
  - setup.bat
  - compile_cl.bat

test_script:
  - build\testencode.exe
  - python.exe run.py
