platform:
  - x86
  - x64

configuration:
  - Release

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"
  - cd test
  - curl -L https://github.com/zxing/zxing/archive/00f634024ceeee591f54e6984ea7dd666fab22ae.zip -o zxing.zip
  - unzip -q zxing.zip -d zxing
  - mkdir zxing\zxing-00f634024ceeee591f54e6984ea7dd666fab22ae\cpp\build
  - cd zxing\zxing-00f634024ceeee591f54e6984ea7dd666fab22ae\cpp\build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=$(configuration) ..
  - nmake
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - mkdir build
  - cp zxing\zxing-00f634024ceeee591f54e6984ea7dd666fab22ae\cpp\build\zxing.exe build\zxing.exe
  - cd ..
  - set VCINSTALLDIR=


build_script:
  - compile_cl.bat
  - cd test
  - compile_cl.bat

after_build:
  - 7z a qrencode.zip %APPVEYOR_BUILD_FOLDER%\build\qrencode.exe

test_script:
  - build\testencode.exe
  - python.exe run.py

artifacts:
  - path: qrencode.zip
    name: qrencode
    type: zip