platform:
  - x86
  - x64

configuration:
  - Release


build_script:
  - compile_cl.bat
  - cd test
  - compile_cl.bat
  - setup.bat

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\qrencode.zip %APPVEYOR_BUILD_FOLDER%\build\qrencode.exe

test_script:
  - build\testencode.exe
  - python.exe run.py

artifacts:
  - path: qrencode.zip
    name: qrencode
    type: zip