platform:
  - x86
  - x64

install:
  - "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd test
  - python.exe setup.py

build_script:
  - compile_cl.bat

test_script:
  - build\testencode.exe
  - python.exe run.py
